{
  imports = [
    ./anki-api
    ./anki-sync-server
    ./atuin
    ./bazarr
    ./cloudflare-warp
    ./cloudflared
    ./prowlarr
    ./qbittorrent
    ./evolution-data-server
    ./flaresolverr
    ./forgejo
    ./home-assistant
    ./immich
    ./jellyfin
    ./jellyseerr
    ./nextcloud
    ./radarr
    ./sonarr
    ./traefik
    ./vaultwarden
  ];
}
